export const userTypes = {
  SET_CURRENT_USER_START: "SET_CURRENT_USER_START",
  SET_CURRENT_USER_SUCCESS: "SET_CURRENT_USER_SUCCESS",
  SET_CURRENT_USER_FAIL: "SET_CURRENT_USER_FAIL",
  LOGOUT_USER: "LOGOUT_CURRENT_USER"
};
